spring.profiles.active=dev
spring.application.name=EvoSchema
logging.config=classpath:${profiles.prefixpath}/log4j2.xml

evoschema.tx.useAtomikos=true
spring.jta.atomikos.properties.max-timeout=3000000
spring.jta.atomikos.properties.default-jta-timeout=3000000
